# Generated by Django 6.0 on 2025-12-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeBase', '0004_course_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='unique_course_slug_per_category'),
        ),
    ]
